### ISSUE TITLE
When the key is pressed multiple time

### ISSUE THREAD

**Issue by SebDominguez** [patrickshox/Keys#1]
When I press the shortcut keys to generate the links multiple time the links became "red" and then "line-through". Then nothing happened. I don't know if this is an intended behavior

<img width="991" alt="Capture d’écran 2020-01-23 à 17 39 13" src="https://user-images.githubusercontent.com/52816569/73004536-ccce8080-3e07-11ea-84de-b078afdd1583.png">

**Comment by patrickshox** [comment]
Thanks for checking it out! 😁 The intended behavior is that as you type, keys that aren’t compatible with what you’ve typed will be crossed out. So for example if you activate keys and then type “M”, all keys that don’t begin with L should be crossed out. On the other hand, keys that do begin with M should have a green M and the rest of the key shouldn’t be crossed out. I submitted version 2.2 without sufficiently testing it, so it had some serious oversights in terms of the activation key. Specifically, when users activate, then click away, and then try to activate a second time. Version 2.3 has been submitted to App Store Connect and will likely be available tonight. Hopefully it will resolve your issue, but I also can’t tell exactly whether that’s an issue or normal behavior.

**Comment by SebDominguez** [comment]
Ok thanks for your quick reply, I'll update the app as soon as it became available on the MAS
