### ISSUE TITLE
Option to only navigate without having to shift

### ISSUE THREAD

**Issue by faridrb** [patrickshox/Keys#12]
Would it be a possibility to create links with only lower case letters. I find it faster to type more letters and not use the shift button. Maybe this can be an option that can be toggled?

**Comment by patrickshox** [comment]
It is already not necessary to use the shift key when typing shortcuts (even those containing uppercase letters). For example, the link "**Is**sue" can be clicked by typing "gis".

**Comment by patrickshox** [comment]
Typing shortcut keys is already case-insensitive. For example, one may click the link "**_Ke_**ys" simply by typing "g k e" (all lowercase).
