### ISSUE TITLE
Extensions doesnt seem to work

### ISSUE THREAD

**Issue by GitHubswn** [patrickshox/Keys#13]
When I tried to activate (check) the extension on Safari's preference it doesnt check, I click on it and it doesnt check.

what could be wrong?

**Comment by patrickshox** [comment]
Hm. From what I can tell, users of many extensions are experiencing [this issue](https://www.reddit.com/r/MacOS/comments/ez5eud/cant_enable_extensions_in_safari_10153/). It seems like a niche issue, but at least a couple people had luck switching between preferences panes. Wish I could be more help, but it seems like a more general MacOS issue.

**Comment by GitHubswn** [comment]
Yes, I just noticed that, all my extensions arent checking back once I unchecked it.

**Comment by TrevorStevenson** [comment]
@patrickshox I will file a bug report internally at Apple in June!
