### ISSUE TITLE
Hotkey does not work while a text field has focus. Therefore a different hotkey is needed

### ISSUE THREAD

**Issue by beyondcompute** [patrickshox/Keys#16]
`g` hotkey does not work, obviously, while you are typing. Which defeats the idea of keyboard-based navigation.

**Comment by melgu** [comment]
You can exit pretty much every text field with the Tab key.

**Comment by patrickshox** [comment]
Escape works as well. Also within the app, you can set it to not allow text fields to steal cursor focus on page load.
