### ISSUE TITLE
Disable Keys on specific website

### ISSUE THREAD

**Issue by uetchy** [patrickshox/Keys#2]
Twitter already offers the "g" action, which is conflicted with Keys behavior and creating unwanted effects.

I'd like to disable Keys on a specific site or change trigger shortcut other than `g`.

**Comment by psculthorpe** [comment]
Hey, I just installed this app and found you can change the shortcut key, but I found it totally by accident...

Load the Keys.app app, then click on the red keyboard key image in the window and type your new key. Very hidden - it would be better if it was a normal looking preference window.

**Comment by patrickshox** [comment]
Version 3.2 of Keys makes it clearer that the activation key is customizable. A blacklist would definitely be a great feature to have, but it seems pretty time consuming to implement so I'm not sure if it's worth it tbh. Thanks for taking the time to open an issue.
<img width="510" alt="Screen Shot 2020-02-17 at 5 35 49 AM" src="https://user-images.githubusercontent.com/47332449/74646220-66f3c100-5147-11ea-9a50-bfe68da7218a.png">

**Comment by otterley** [comment]
Gmail also uses `g` as a shortcut key if you have keyboard shortcuts available.  I too would like to see a blacklist so that I can continue to use this extension.

**Comment by patrickshox** [comment]
3 months late, a6d4612 adds a basic blacklist. Version 3.4 of Keys will include it. Thanks for the suggestion @otterley & @uetchy.
