### ISSUE TITLE
Unable to Activate Extension

### ISSUE THREAD

**Issue by djfdat** [patrickshox/Keys#21]
Safari Version 13.1 (15609.1.20.111.8)
Catalina 10.15.4 (19E287)

No matter what I try, I am unable to activate the extension the the Safari Extension Preferences.

When I try to activate the checkbox, nothing happens. I do have other extensions installed and activated, but am unable to do so for Keys.

I have tried uninstalling/reinstalling, quitting and reopening safari, but nothing seems to do the trick.

**Comment by djfdat** [comment]
Actually, this appears to be a Safari issue and not a Keys issue. Looking around it seems that there are reports for this same issue with 1Password. Their recommended solution was to uninstall and then reinstall from the website instead of the App Store.
Also, I wasn't able to enable other extensions, and, I stupidly turned off my working extensions and am now unable to turn them back on. 
:/

**Comment by patrickshox** [comment]
I agree that it's a more general Safari issue that my friend (who will work on the Safari team at Apple) is aware of (see #13). [Some people](https://www.reddit.com/r/MacOS/comments/ez5eud/cant_enable_extensions_in_safari_10153/) have found that switching between Safari preference panes fixes the issue. I'm happy to reimburse you if you have Apple Pay and are willing to DM me your iPhone number on Reddit (u/patrickshox).

**Comment by djfdat** [comment]
Thank for the refund offer, but I think I'll hold on to it until it works. I am excited to try it!
