### ISSUE TITLE
Can not disable "⌘G to open background tab" 

### ISSUE THREAD

**Issue by kpry** [patrickshox/Keys#26]
After disabling "⌘G to open background tab", it is always enabled when relaunching the app.

Animated gif attached showing the symptom.

![Keys Issue](https://user-images.githubusercontent.com/4054334/98450190-5550b000-2100-11eb-96b7-b6e43fbf5154.gif)

**Comment by patrickshox** [comment]
Thank you for bringing this to my attention! Clearly, I should have tested this version more thoroughly. I copied and pasted a lot of the logic from the "enableFocus" actions to the "enableModifier" action. Unfortunately, I got sloppy and forgot to change which checkbox the enableModifier action references, meaning it would always match the first checkbox. Fixing [one line ](https://github.com/patrickshox/Keys/blob/1941fd8281a66db77c93138d538f8038c78c9c02/Keys/ViewController.swift#L33) resolves this issue.
