### ISSUE TITLE
swap to another color

### ISSUE THREAD

**Issue by charles-e** [patrickshox/Keys#29]
Red is great for your links *but* it does not show up when the links are *already red*.  I ran in to this situation while kicking the tires on this [page](https://meowni.ca/posts/tree-rings/).  If there is a clever way to switch the generated shortcuts color from red to green that would be an important improvement.  E.g. hit shift-g', to get green instead of red.

**Comment by charles-e** [comment]
Your app is so elegant, handy and powerful.  I am sorry if my suggestion makes it a little less elegant.

**Comment by patrickshox** [comment]
The way stylesheets are injected in a Safari Extension is actually pretty rigid. I'm sure there's a way to add stylesheets and rules programmatically via the injected script on a per website basis, but honestly it's a bit too niche a problem for me to spend that much time on. There are over 1.8 billion websites, so no extension will ever work perfectly on every site. If a SafariExtensionHandler API ever becomes available that makes it easy to change stylesheet rules, I'll consider implementing it.
