### ISSUE TITLE
Don't activate when using modifier keys

### ISSUE THREAD

**Issue by rik** [patrickshox/Keys#3]
I'm often using Cmd-G to "Find next" and it now triggers the Keys extension. It would be nice if it didn't.

**Comment by patrickshox** [comment]
Good idea 👍. The latest commit addresses this issue. Version 3.2 of Keys on the Mac App Store will as well.
https://github.com/patrickshox/Keys/blob/35128b84e0fe847006ddb0556b203f0cce7026bf/Keys%20Extension/Keys.js#L36
