### ISSUE TITLE
Frame support

### ISSUE THREAD

**Issue by frank-f** [patrickshox/Keys#4]
Hi,

I'd love to see HTML frames supported. At the moment only one frame gets hotkeys while the others can't be navigated to with the keyboard at all. Perfect would be hotkeys in all frames at once, but if that's not possible, maybe you can add a way to switch between frames?

Regards!

**Comment by patrickshox** [comment]
I think if the frame and page are from different sites, the same-origin policy would prevent it. With respect to switching frames, I like the idea but it sounds too time consuming to implement to be honest. Thanks for the issue!
