### ISSUE TITLE
More prominent link design needed

### ISSUE THREAD

**Issue by psculthorpe** [patrickshox/Keys#5]
Having used Vimari on Safari a lot, I am finding the simple highlighting of characters in red to not be enough to really stand out in comparison.

Vimari uses a yellow background and think black lettering.

I appreciate keys is doing things differently in that it applies an inline style to the characters, but if there was some way of better highlighting the shortcut keys (like you are doing with image overlays) I think it would make for a much better experience.

**Comment by beyondcompute** [comment]
I strongly agree, design like the one on the picture below works better:
![screenshot](https://user-images.githubusercontent.com/248055/76307477-907cb400-62d1-11ea-9b1c-75c99bad8e2f.png)

Thanks for the great extension, by the way!

**Comment by beyondcompute** [comment]
Also it obstructs some short links. Example on Facebook (the last four):
<img width="410" alt="Screenshot 2020-03-10 at 13 48 09" src="https://user-images.githubusercontent.com/248055/76309623-d20f5e00-62d5-11ea-82c3-899b370e9b70.png">

**Comment by patrickshox** [comment]
That's fair but the intention of the extension is to be more aesthetically pleasing (and better able to handle scrolling than apps like Vimari). I also just don't see the point in implementing something like that when Vimari exists and is free for users who prefer that.
