### ISSUE TITLE
The app didn't worked on my environment and tried to investigate the problem

### ISSUE THREAD

**Issue by LEoREo2247** [patrickshox/Keys#9]
Hi, I discovered your project few days ago and I absolutely love the concept, but the app seems to be not functioning at all on my environment. I'm using MBP 13 2014 with Japanese keyboard layout on macOS 10.15.1 and Safari 13.0.3.

https://streamable.com/nhzzo
(Trying to press "ts" for the link "Contents" at the left menu)

As you can see, the activation(trigger) key does work and it shows all the keyboard shortcuts up on every links on the page. But all shortcut letters will get line-through as soon as I press any key after triggering Keys.

I looked into the code and found that the app will work as intended without concatenating a letter created from the keycode of the pressed letter, to the value of the hidden input element for catching a key events.

https://github.com/patrickshox/Keys/blob/4fbefcb2c94166d185ea4dd629f87cc95f1c38aa/Keys%20Extension/Keys.js#L397

The part `.concat(String.fromCharCode(keypress.which).toLowerCase())` seems unneeded to my untrained eye, as I figured that the keycode which can be obtained from keydown event are always 229(which corresponds to "å") on Safari regardless of the key actually pressed, while Chrome and Firefox both return the appropriate keycode.
Addition of this letter("å") at the end of the value of the input element and using that as a search text seems to be causing all shortcut letters on the page to immediately get unmatched with the search text at the moment of first key input - at least of my end.

Would you kindly explain me what this addition of the letter exactly does for what purpose? And if this behavior is intended, I suppose the app is working for majority of people, but do you have any idea on why it is not working and how could I possibly fix it on my end? Thank you so much!

**Comment by patrickshox** [comment]
Thanks for bringing this to my attention and thanks for investigating the issue!! This issue is resolved in the most recent commit, and will be fixed in version 3.2 of Keys. If you're interested, the issue has to do with the Japanese keyboard, which replaces Latin with Japanese characters. To patch it, searchText is now constructed by interpreting the keypress events, rather than by reading the value of the hidden input field.

**Comment by LEoREo2247** [comment]
Great to hear that! Thank you for looking into this :)
